aws_region = "us-east-1"
s3_bucket_remote_state = "terraform-store-lambda-statefile-module"
commit_sha = ""
s3_lambda_trigger_bucket_name = "s3-bucket-lambda-trigger-tfmodule"
ecr_repo = "lambda-repo"
username = "AWS"
ecr_image_tag = "latest-test"
lambda_path = "modules/lambda/lambda_function"